env:
  commonjs: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  BigInt: true
parserOptions:
  ecmaVersion: 11
rules: {
  "semi": ["error", "always"]
}