language: node_js
node_js:
- iojs
- '0.10'
- '0.12'
before_script:
- npm install -g istanbul
- npm install -g mocha
- npm install -g coveralls
after_script:
- npm run coverage
- npm run coveralls
notifications:
  slack:
    secure: Q2YBqXEyZmq5bsFStTRrpcnEunI3+FlglsJhb4pvXi2nZP80Z7IwpY3BZj7U8UeICmBGPazFF5z7ZW9fpiENdbvMvgYs+OZPsyBeT17Zx5qqsgFYRC73q/Uzst3bbEgvBa4eMkhbUTXmJNSh/hWB1I7M79pdUie0VC3d2LenoriGlTUrPTICwqv36olZmpaLeKq9/80zfFz8Sk4tCYQZBU5vp2XysfQmL83n1EiZadxafb2RfYttMEdnTmH8Y8/Omd3pNa8KI3WHHebEBajvHxH/EEDnzQW/Kh1uoeidFoccgyTp8UNKfLW2TvGMwIkDmwGUQlaf6XB8UTONbi/nw8Z9LyQTKKc8FfXG89hdR/erDlnmtC56rFjCV0rzVCWGCMZRoNHnKrSLvtm1egqr4miorfsDOnGRKxwd9dQE1XmLEHzvlgQewb8jyCmtoCw7b4KUWFfyplzr1SRNAjydBWcIgIGP/EoJrdVVYaUXjcVSSaMJV0uVxQFhyGYL7AXAh13TRJ5ku4PnLIP8+WbEc3XCA+AQu/CLyoqRc46LwPAskaBpwh0T3KKfznPCJoiTMKSai1kbhJOb4v0StkqKTrtS4gLFFTiBwYWm+oKt1znrG0zdxhMu0XmVjrfHuHkH6kR4CftlDgfWnptkzubYHpjPbL4YRiRyZqROoiKKMzc=
